---
title: "OSM Data Wrangling"
output: html_document
date: "2023-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

## R Markdown

```{r}
library(osmdata)
library(sf)
library(ggplot2)
library(raster)
library(dplyr)
library(readr)

# Capture the start time
start_time <- Sys.time()
```

## Setting Parameters
```{r}
# coordinate_system <- 32756
# 
# resolution <- 300

coordinate_system <- 4326
# Target resolution in m
resolution <- 30
# Conversion to degrees
resolution <- (resolution/30)/3600

```

```{r, echo=FALSE}
# Load required libraries
library(raster)
library(ncdf4)

# Specify the path to your NC4 file
nc4_file_path <- "path/to/your/file.nc4"

# Open the NC4 file
nc_data <- nc_open(nc4_file_path)

# Print the names of variables in the NC4 file to identify which one you want to convert
print(nc_var_get_names(nc_data))

# Assuming the variable you want to convert is named 'your_variable_name'
variable_name <- 'your_variable_name'

# Read the variable data
variable_data <- raster(ncvar_get(nc_data, variable_name))

# If the NC4 file contains lat-lon information, set the projection
crs(variable_data) <- CRS("+proj=longlat +datum=WGS84")
  
# Set the filename for the output raster
output_raster_filename <- "output_raster.tif"

# Write the raster to a file
writeRaster(variable_data, filename=output_raster_filename, format="GTiff", overwrite=TRUE)

# Close the NC4 file
nc_close(nc_data)

```


```{r, echo=FALSE}
# Reclassify rasters
# Define reclassification rules
# Format: c(start, end, newvalue)
reclass_matrix <- matrix(c(0, 0, 1,
                           1, 1, 1,
                           2, 2, 2,
                           3, 3, 3,
                           4, 4, 4,
                           5, 5, 1), ncol = 3, byrow = TRUE)

# Apply the reclassification
lc_2013 <- reclassify(lc_2013, reclass_matrix)
lc_2023 <- reclassify(lc_2023, reclass_matrix)

```


```{r, echo=FALSE}
# Project the rasters
# lc_2013 <- projectRaster(lc_2013, crs = coordinate_system, method = "ngb")
# lc_2023 <- projectRaster(lc_2023, crs = coordinate_system, method = "ngb")
pop2010 <- projectRaster(pop2010, crs = coordinate_system, method = "bilinear")
pop2020 <- projectRaster(pop2020, crs = coordinate_system, method = "bilinear")
slope <- projectRaster(slope, crs = coordinate_system, method = "bilinear")
wdpa <- projectRaster(wdpa, crs = coordinate_system, method = "ngb")
```
```{r}
# Resample each raster to match the resolution of prox_road
lc_2013 <- resample(lc_2013, dist_road, method = "ngb")
lc_2023 <- resample(lc_2023, dist_road, method = "ngb")
dist_highway <- resample(dist_highway, dist_road, method = "bilinear")
pop2010 <- resample(pop2010, dist_road, method = "bilinear")
pop2020 <- resample(pop2020, dist_road, method = "bilinear")
slope <- resample(slope, dist_road, method = "bilinear")
wdpa <- resample(wdpa, dist_road, method = "ngb")
```


```{r, echo=FALSE}
# Clip the rasters with the polygon
lc_2013 <- crop(lc_2013, cropbox)
lc_2023 <- crop(lc_2023, cropbox)
dist_road <- crop(dist_road, cropbox)
dist_highway <- crop(dist_highway, cropbox)
pop2010 <- crop(pop2010, cropbox)
pop2020 <- crop(pop2020, cropbox)
slope <- crop(slope, cropbox)
wdpa <- crop(wdpa, cropbox)

```

```{r}
plot(lc_2013)
plot(lc_2023)
plot(pop2010)
plot(pop2020)
plot(dist_road)
plot(dist_highway)
plot(slope)
plot(wdpa)
```


```{r, echo=FALSE}
# Check for Uniformity of raster data
# Check Resolution
res(lc_2013)
res(lc_2023)
res(dist_road)
res(dist_highway)
res(pop2010)
res(pop2020)
res(slope)
res(wdpa)

# Check Extents
extent(lc_2013)
extent(lc_2023)
extent(dist_road)
extent(dist_highway)
extent(pop2010)
extent(pop2020)
extent(slope)
extent(wdpa)

# Check Coordinate Systems
crs(lc_2013)
crs(lc_2023)
crs(dist_road)
crs(dist_highway)
crs(pop2010)
crs(pop2020)
crs(slope)
crs(wdpa)

```

```{r}
# Make RasterStacks
LandCover <- stack(lc_2013, lc_2023)
names(LandCover) <- c("lc2013", "lc2023")

Factors <- stack(pop2010, slope, wdpa, dist_road, dist_highway)
names(Factors) <- c("ef_01", "ef_02", "ef_03","ef_04","ef_05")
  
# names(SanJose)
for(i in 1:nlayers(LandCover)) {
  print(unique(values(LandCover[[i]])))}

# Define the reclassification matrix
reclass_matrix <- matrix(c(0, 0, 1,
                           1, 1, 1,
                           2, 2, 2,
                           3, 3, 3,
                           4, 4, 4,
                           5, 5, 1), ncol = 3, byrow = TRUE)

# Function to reclassify a raster layer
reclassify_raster <- function(raster_layer) {
  reclassify(raster_layer, reclass_matrix, right=NA)}

# Apply the reclassification to each layer in the RasterStack
LandCover <- stack(lapply(1:nlayers(LandCover), function(i) reclassify_raster(LandCover[[i]])))

# Check the unique values again
for(i in 1:nlayers(LandCover)) {
  print(unique(values(LandCover[[i]])))}
```

```{r}
# Set Directory
setwd("/Users/oliveratwood/Documents/GitHub/HotspotStoplight/UrbanExpansion/data")

save(LandCover, file = "LandCover.RData")
save(Factors, file = "Factors.RData")

```

```{r}
# Save the rasters to the directory
# setwd("/Users/oliveratwood/Documents/GitHub/HotspotStoplight/UrbanExpansion/data/test")
# 
# writeRaster(lc_2013, filename = "Landcover_Landsat8_2013_2014_CostaRica_SanJose.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(lc_2023, filename = "Landcover_Landsat9_2022_2023_CostaRica_SanJose.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(dist_road, filename = "roads_proximity.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(dist_highway, filename = "highway_proximity.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(pop2010, filename = "Pop_2010_Crop4.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(pop2020, filename = "Pop_2020_Crop4.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(slope, filename = "Slope.tif", format = "GTiff", overwrite=TRUE)
# writeRaster(wdpa, filename = "wdpa.tif", format = "GTiff", overwrite=TRUE)
```



```{r timer_end}
# Capture the end time
end_time <- Sys.time()

# Calculate and print the runtime
runtime <- end_time - start_time
print(paste("Total runtime:", runtime))
```

