---
title: "Raster Pre-Processing"
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

## R Markdown

```{r}
library(osmdata)
library(sf)
library(ggplot2)
library(raster)
library(dplyr)
library(readr)
library(terra)
library(corrplot)
library(viridis)


# Capture the start time
start_time <- Sys.time()
```

## Setting Parameters
```{r}
# coordinate_system <- 32756

coordinate_system <- 4326

# Target resolution in m
resolution_meters <- 30
# resolution_meters <- 60
# resolution_meters <- 100

# Conversion to degrees
resolution_degrees <- resolution_meters / (30*3600)

# Read the GeoJSON file for cropbox
cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop_SJ_Region.geojson")
# cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop4.geojson")
# Crop5a is the largest cropbox that can be used for the land cover change prediction at 30m resolution on OA's Macbook
# cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop5a.geojson")
# cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop5c.geojson")
# cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop6.geojson")



```

```{r, echo=FALSE}

# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop5c_60m'
# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop5c_30m'
# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop6_30m'
# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop4_100m'
# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop4_60m'
# outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/crop4_30m'
outputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/cropped/CR_Crop_SJ_Region'

# Base directory
inputs <- '/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/'

# List of file names
filenames <- c('sanjose2013bespoke_updatedFandNF_march20.tif', 'sanjose2023bespoke_updatedFandNF_march20.tif', 'roads_proximity.tif', 'highway_proximity.tif', 'population2018.tif', 'Slope.tif', 'dist2urban.tif')
# filenames <- c('sanjose2013bespoke.tif', 'sanjose2023bespoke.tif', 'roads_proximity.tif', 'highway_proximity.tif', 'population2018.tif', 'Slope.tif', 'dist2urban.tif')

# List of desired variable names corresponding to each file
var_names <- c('lc_2013', 'lc_2023', 'dist_road', 'dist_highway', 'pop2018', 'slope', 'dist_urban')

# Loop through each file name
for (i in 1:length(filenames)) {
  # Generate the full path for the current file
  full_path <- file.path(inputs, filenames[i])
  
  # Create a raster object from the file
  temp_raster <- raster(full_path)
  
  # Dynamically assign the raster object to a variable with the name from var_names
  assign(var_names[i], temp_raster)
}

# # Load files from github
# # LAND COVER 2013
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/sanjose2013bespoke.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# lc_2013 <- raster(temp)
# 
# # LAND COVER 2023
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/sanjose2023bespoke.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# lc_2023 <- raster(temp)
# 
# # DISTANCE TO ROADS
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/roads_proximity.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# dist_road <- raster(temp)
# 
# # DISTANCE TO HIGHWAYS
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/highway_proximity.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# dist_highway <- raster(temp)
# 
# 
# # POPULATION 2018
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/population2018.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# pop2018 <- raster(temp)
# 
# # # POPULATION 2010
# # url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/Pop_2010_Crop4.tif"
# # temp <- tempfile(fileext = ".tif")
# # download.file(url, temp, method = "auto")
# # pop2010 <- raster(temp)
# # 
# # # POPULATION 2020
# # url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/Pop_2020_Crop4.tif"
# # temp <- tempfile(fileext = ".tif")
# # download.file(url, temp, method = "auto")
# # pop2020 <- raster(temp)
# 
# # SLOPE
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/Slope.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# slope <- raster(temp)
# 
# # DISTANCE TO URBAN LAND COVER
# url <- "https://github.com/HotspotStoplight/LandCoverChange/raw/main/data/inputs/dist2urban.tif"
# temp <- tempfile(fileext = ".tif")
# download.file(url, temp, method = "auto")
# dist_urban <- raster(temp)


```
```{r}
# extent(lc_2013)
# extent(lc_2023)
```


```{r, echo=FALSE}
# Project the rasters
# pop2010 <- projectRaster(pop2010, crs = coordinate_system, method = "bilinear")
# pop2020 <- projectRaster(pop2020, crs = coordinate_system, method = "bilinear")
# pop2018 <- projectRaster(pop2018, crs = coordinate_system, method = "bilinear")
# 
# setwd("/Users/oliveratwood/Documents/GitHub/HotspotStoplight/LandCoverChange/data/inputs/")
# 
# # Export the raster as a GeoTIFF
# output_filename <- "population2018.tif"
# writeRaster(pop2018, filename=output_filename, format="GTiff", overwrite=TRUE)

```

```{r}
# Extract extent and crs from cropbox
bbox <- st_bbox(cropbox)
extent <- as(extent(bbox), "Extent")
crs <- crs(cropbox)
res <- resolution_degrees

# Calculate the number of columns and rows based on the resolution and the extent
nrows <- ceiling((extent@ymax - extent@ymin) / resolution_degrees)
ncols <- ceiling((extent@xmax - extent@xmin) / resolution_degrees)

# Create an empty raster with the specified extent, resolution, and CRS
# Here, we manually specify xmn, xmx, ymn, ymx based on the extent object
r <- raster(nrows=nrows, ncols=ncols, xmn=extent@xmin, xmx=extent@xmax, ymn=extent@ymin, ymx=extent@ymax, crs=crs)

```
# Resample Rasters
```{r}
# # For categorical data, we use mode-based resampling
# # Define a custom function to calculate the mode
# modeFun <- function(x, ...) { 
#   ux <- unique(na.omit(x))
#   if (length(ux) == 0) return(NA)  # Handle case where all values are NA
#   ux[which.max(tabulate(match(x, ux)))]
# }
# 
# processRaster <- function(sourceRaster, targetRaster) {
#   # Ensure alignment to the target raster's grid, regardless of aggregation
#   if (res(sourceRaster)[1] != res(targetRaster)[1]) {
#     # Perform aggregation or disaggregation as necessary
#     factor <- res(targetRaster)[1] / res(sourceRaster)[1]
#     if (factor > 1) {
#       # Aggregate using custom mode function
#       aggregatedRaster <- aggregate(sourceRaster, fact=round(factor), fun=modeFun)
#       cat("Aggregated raster resolution:", res(aggregatedRaster), "\n")
#       resampledRaster <- projectRaster(aggregatedRaster, targetRaster, method="ngb")
#     } else {
#       # Disaggregation (higher resolution) - use resampling
#       resampledRaster <- resample(sourceRaster, targetRaster, method="ngb")
#     }
#   } else {
#     # Directly align to target raster without changing resolution
#     resampledRaster <- projectRaster(sourceRaster, targetRaster, method="ngb")
#   }
#   return(resampledRaster)
# }

processRaster <- function(sourceRaster, targetRaster) {
  # Ensure all open connections are closed upon function exit
  on.exit({
    closeAllConnections()  # Close all remaining open connections
  }, add = TRUE)

  cat("Starting raster processing\n")
  cat("Source resolution: ", res(sourceRaster), "\n")
  cat("Target resolution: ", res(targetRaster), "\n")

  # Use resample with nearest neighbor method for categorical data
  resampledRaster <- resample(sourceRaster, targetRaster, method="ngb")
  cat("Resampling completed with nearest neighbor method\n")
  cat("Resampled raster resolution: ", res(resampledRaster), "\n")

  cat("Raster processing completed\n")
  return(resampledRaster)
}


# Process both rasters to match the resolution and extent of the created empty raster 'r'
lc_2013 <- processRaster(lc_2013, r)
lc_2023 <- processRaster(lc_2023, r)

```

```{r}
# For non-categorical data, we can use bilinear resampling
pop2018 <- resample(pop2018, r, method = "bilinear")
slope <- resample(slope, r, method = "bilinear")
dist_road <- resample(dist_road, r, method = "bilinear")
dist_highway <- resample(dist_highway, r, method = "bilinear")
```


```{r, echo=FALSE}
# Clip the rasters with the polygon
lc_2013 <- crop(lc_2013, cropbox)
lc_2023 <- crop(lc_2023, cropbox)
dist_road <- crop(dist_road, cropbox)
dist_highway <- crop(dist_highway, cropbox)
pop2018 <- crop(pop2018, cropbox)
slope <- crop(slope, cropbox)
```

Input Land Cover Raster Classification Schema (Tristan Grupp, old)
0 - water 
1 - non-forest
2 - forest
3 - no data
4 - urban

new
1 - non-forest
2 - forest
3 - urban
4 - water 
0 - no data

Target Land cover classification schema
1 - forest
2 - non-forest
3 - urban
4 - water

```{r}
# Define the reclassification matrix
reclass_matrix <- matrix(c(0, 0, 4,  # Water to 4
                           1, 1, 2,  # Non-forest to 2
                           2, 2, 1,  # Forest to 1
                           3, 3, 1,  # No data to Forest (1)
                           4, 4, 3), # Urban to 3
                         ncol=3, byrow=TRUE)
# reclass_matrix <- matrix(c(0, 0, 1,  # no data to 1 (forest)
#                            1, 1, 2,  # Non-forest to 2 (non-forest)
#                            2, 2, 1,  # Forest to 1 (forest)
#                            3, 3, 3,  # Urban to 3 (urban)
#                            4, 4, 4), # Water to 4 (water)
#                          ncol=3, byrow=TRUE)

# Function to reclassify a raster layer
reclassify_raster <- function(raster_layer) {
  reclassify(raster_layer, reclass_matrix, right=NA)}

lc_2013 <- reclassify_raster(lc_2013)
lc_2023 <- reclassify_raster(lc_2023)
```

```{r}
# Convert the reclassified raster to a binary layer where urban areas are 1 and others are 0
# Assuming urban is represented by the value 3 based on your reclassification
urban_binary <- lc_2013 == 3

# Convert from RasterLayer (raster package) to SpatRaster (terra package)
# Assuming `urban_binary` is your binary raster from the `raster` package
urban_binary_terra <- rast(urban_binary)

# Assuming urban areas are marked as 1 and non-urban areas are 0 in your urban_binary raster
# Convert non-urban areas (0) to NA
values(urban_binary_terra)[values(urban_binary_terra) == 0] <- NA

# Calculate the distance to the nearest urban area (where value is not NA)
urban_distance_terra <- terra::distance(urban_binary_terra)

dist_urban <- raster(urban_distance_terra)
```

```{r}
plot(lc_2013, col=viridis(100))
plot(lc_2023, col=viridis(100))
plot(pop2018, col=viridis(100))
plot(dist_road, col=viridis(100))
plot(dist_highway, col=viridis(100))
plot(slope, col=viridis(100))
plot(dist_urban, col=viridis(100))

```
```{r}
ext(lc_2013)
ext(lc_2023)
ext(pop2018)
ext(dist_road)
ext(dist_highway)
ext(slope)
ext(dist_urban)
```


```{r}
# Make RasterStacks
LandCover <- stack(lc_2013, lc_2023)
names(LandCover) <- c("lc2013", "lc2023")

Factors <- stack(pop2018, slope, dist_urban, dist_road, dist_highway)
names(Factors) <- c("ef_01", "ef_02", "ef_03","ef_04","ef_05")

# Check the unique values again
for(i in 1:nlayers(LandCover)) {
  print(unique(values(LandCover[[i]])))}
```

```{r}
# Set Directory
setwd(outputs)

save(LandCover, file = "LandCover.RData")
save(Factors, file = "Factors.RData")

```


```{r timer_end}
# Capture the end time
end_time <- Sys.time()

# Calculate and print the runtime
runtime <- end_time - start_time
print(paste("Total runtime:", runtime))
```

